/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 10.0.0 -fPIC -Os) */

(* src = "sevenseg.v:1" *)
module sevenseg(HEX0, SW);
  (* src = "sevenseg.v:4" *)
  reg [6:0] _0_;
  (* src = "sevenseg.v:4" *)
  reg [6:0] _1_;
  (* src = "sevenseg.v:1" *)
  output [6:0] HEX0;
  reg [6:0] HEX0;
  (* src = "sevenseg.v:2" *)
  input [3:0] SW;
  always @* begin
    _0_ = _1_;
    casez (SW)
      4'h1:
        begin
          _1_ = 7'h79;
        end
      4'h2:
        begin
          _1_ = 7'h24;
        end
      4'h3:
        begin
          _1_ = 7'h30;
        end
      4'h4:
        begin
          _1_ = 7'h19;
        end
      4'h5:
        begin
          _1_ = 7'h12;
        end
      4'h6:
        begin
          _1_ = 7'h02;
        end
      4'h7:
        begin
          _1_ = 7'h78;
        end
      4'h8:
        begin
          _1_ = 7'h00;
        end
      4'h9:
        begin
          _1_ = 7'h18;
        end
      4'ha:
        begin
          _1_ = 7'h08;
        end
      4'hb:
        begin
          _1_ = 7'h03;
        end
      4'hc:
        begin
          _1_ = 7'h46;
        end
      4'hd:
        begin
          _1_ = 7'h21;
        end
      4'he:
        begin
          _1_ = 7'h06;
        end
      4'hf:
        begin
          _1_ = 7'h0e;
        end
      4'h0:
        begin
          _1_ = 7'h40;
        end
      default:
          _1_ = HEX0;
    endcase
  end
  always @* begin
      HEX0 <= _0_;
  end
endmodule

(* src = "top.v:2" *)
module top(HEX0, HEX1, HEX2, HEX3, HEX4, HEX5, HEX6, HEX7, SW);
  (* src = "top.v:2" *)
  output [6:0] HEX0;
  (* src = "top.v:2" *)
  output [6:0] HEX1;
  (* src = "top.v:2" *)
  output [6:0] HEX2;
  (* src = "top.v:2" *)
  output [6:0] HEX3;
  (* src = "top.v:2" *)
  output [6:0] HEX4;
  (* src = "top.v:2" *)
  output [6:0] HEX5;
  (* src = "top.v:2" *)
  output [6:0] HEX6;
  (* src = "top.v:2" *)
  output [6:0] HEX7;
  (* src = "top.v:3" *)
  input [15:0] SW;
  (* src = "top.v:6" *)
  sevenseg UUD0 (
    .HEX0(HEX0),
    .SW(4'h7)
  );
  (* src = "top.v:7" *)
  sevenseg UUD1 (
    .HEX0(HEX1),
    .SW(4'h1)
  );
  (* src = "top.v:8" *)
  sevenseg UUD2 (
    .HEX0(HEX2),
    .SW(4'h0)
  );
  (* src = "top.v:9" *)
  sevenseg UUD3 (
    .HEX0(HEX3),
    .SW(4'h2)
  );
  (* src = "top.v:10" *)
  sevenseg UUD4 (
    .HEX0(HEX4),
    .SW(SW[3:0])
  );
  (* src = "top.v:11" *)
  sevenseg UUD5 (
    .HEX0(HEX5),
    .SW(SW[7:4])
  );
  (* src = "top.v:12" *)
  sevenseg UUD6 (
    .HEX0(HEX6),
    .SW(SW[11:8])
  );
  (* src = "top.v:13" *)
  sevenseg UUD7 (
    .HEX0(HEX7),
    .SW(SW[15:12])
  );
endmodule
